package errmsg

const (
	SUCCESS = 200
	ERROR   = 500
	// 用户模块
	ERROR_USERNAME_USED    = 1001
	ERROR_PASSWORD_WRONG   = 1002
	ERROR_USER_NOT_EXIST   = 1003
	ERROR_TOKEN_NOT_EXIST  = 1004
	ERROR_TOKEN_RUNTIME    = 1005
	ERROR_TOKEN_WRONG      = 1006
	ERROR_TOKEN_TYPE_WRONG = 1007
	ERROR_USER_NO_RIGHT    = 1008
	// Token
	ERROR_ART_NOT_EXIST = iota + 2001
	ERROR_TOKEN_FORMAT
	// 分类模块
	ERROR_CATENAME_EXITS = iota + 3001
	ERROR_CATENAME_USED
	ERROR_CATENAME_FORMAT
	REEOR_CATE_ADD_FAIL
	ERROR_CATEGORY_BY_ID_NOT_EXIST
	ERROR_CATEGORY_UPDATE_FAIL
	// 文章帖子
	ERROR_REQUERY_ARG_WRONG = 4000
	ERROR_ARTICLE_CONTENT   = iota + 4001
	ERROR_ARTICLE_ERROR
	ERROR_ARTICLE_ADD_FAIL
	ERROR_ARTICLE_UPDATE_FAIL
	ERROR_ARTICLE_DELETE_FAIL
	ERROR_TYPE_ASSERTION
)

var codeMsg = map[int]string{
	SUCCESS:                 "OK",
	ERROR:                   "FAIL",
	ERROR_REQUERY_ARG_WRONG: "请求参数错误",
	// 用户模块
	ERROR_USERNAME_USED:    "用户名已存在！",
	ERROR_PASSWORD_WRONG:   "密码错误",
	ERROR_USER_NOT_EXIST:   "用户不存在",
	ERROR_TOKEN_NOT_EXIST:  "TOKEN不存在",
	ERROR_TOKEN_RUNTIME:    "TOKEN已过期",
	ERROR_TOKEN_WRONG:      "TOKEN不正确",
	ERROR_TOKEN_TYPE_WRONG: "TOKEN格式错误",
	ERROR_USER_NO_RIGHT:    "该用户无权限",
	// 分类模块
	ERROR_CATENAME_USED:            "分类已存在",
	ERROR_CATENAME_EXITS:           "分类不存在",
	ERROR_CATENAME_FORMAT:          "分类格式错误",
	ERROR_CATEGORY_BY_ID_NOT_EXIST: "分类ID不正确",
	ERROR_CATEGORY_UPDATE_FAIL:     "分类更新失败",
	REEOR_CATE_ADD_FAIL:            "添加分类失败",
	// 文章模块
	ERROR_TYPE_ASSERTION:      "类型错误的",
	ERROR_ART_NOT_EXIST:       "文章不存在",
	ERROR_ARTICLE_CONTENT:     "没有文章内容",
	ERROR_ARTICLE_ERROR:       "提交数据错误",
	ERROR_ARTICLE_ADD_FAIL:    "添加文章失败",
	ERROR_ARTICLE_UPDATE_FAIL: "跟新文章失败",
	ERROR_ARTICLE_DELETE_FAIL: "删除文章失败",
}

func GetErrMsg(code int) string {
	return codeMsg[code]
}
